apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: togglemaster
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9SRVBMQUNFX01F
  MASTER_KEY: UkVQTEFDRV9NRQ==

---
apiVersion: v1
kind: Secret
metadata:
  name: flag-service-secrets
  namespace: togglemaster
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9SRVBMQUNFX01F

---
apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secrets
  namespace: togglemaster
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9SRVBMQUNFX01F

---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secrets
  namespace: togglemaster
type: Opaque
data:
  REDIS_URL: cmVkaXM6Ly9SRVBMQUNFX01F
  SERVICE_API_KEY: UkVQTEFDRV9NRQ==
  AWS_SQS_URL: aHR0cHM6Ly9SRVBMQUNFX01F

---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secrets
  namespace: togglemaster
type: Opaque
data:
  AWS_SQS_URL: aHR0cHM6Ly9SRVBMQUNFX01F

